spring:
  application:
    name: msif
    security:
      jwt:
        secret-key: qrVEBGGghpkc9Ra5L1ELHxm6gisrpgMw,
        expiration: 1800000,
        refresh-token:
          expiration: 604800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        query:
          in_clause_parameter_adding: true
  datasource:
    url: jdbc:mysql://localhost:3306/msif_ninos_felices
    username: root
    password: mysql
    hikari:
      maximum-pool-size: 3